solution
mate-academy/react_counter pull request #1313
Opened 2023-01-03 21:29 UTC by batstolya

[DEMO LINK](https://batstolya.github.io/react_counter/)

2023-01-03 23:52 UTC, olena-yanovska requested changes

2023-01-03 23:52 UTC, olena-yanovska commented on src/App.tsx
> +    });
```suggestion
this.setState((state) => ({
      count: state.count + 100,
    }));
```

2023-01-03 23:52 UTC, olena-yanovska commented on src/App.tsx
> +    });
```suggestion
   this.setState((state) => ({
      count: state.count + 1,
    }));
```

2023-01-03 23:54 UTC, olena-yanovska requested changes
Nice! Just make a code a little shorter

2023-01-04 13:38 UTC, olena-yanovska approved these changes

2023-01-04 15:30 UTC, solaryasha approved these changes
Cool UI, i like it!

2026-07-13 23:07 UTC, closed without merging