add task solution
mate-academy/react_counter pull request #1785
Opened 2023-09-02 17:51 UTC by ogospadzipalina

[DEMO LINK](https://ogospadzipalina.github.io/react_counter/)

2023-09-04 06:37 UTC, choeqq requested changes

2023-09-04 06:37 UTC, choeqq commented on src/App.tsx
> +    this.setState(PrevState => ({ count: PrevState.count + 1 }));
```suggestion
    this.setState(prevState => ({ count: prevState.count + 1 }));
```

2023-09-04 06:37 UTC, choeqq commented on src/App.tsx
> +    this.setState(PrevState => ({ count: PrevState.count + 100 }));
```suggestion
    this.setState(prevState => ({ count: prevState .count + 100 }));
```

2023-09-04 08:31 UTC, closed without merging

2023-09-04 11:44 UTC, domalewski approved these changes
LGTM

2023-09-05 06:41 UTC, choeqq approved these changes