solution
mate-academy/react_counter pull request #186
Opened 2020-09-05 11:24 UTC by Oleksandr-Rohatnov

[DEMO LINK](https://Oleksandr-Rohatnov.github.io/react_counter/)

2020-09-06 16:31 UTC, karinaKudatska approved these changes

2020-09-07 06:44 UTC, irenhh requested changes

2020-09-07 06:44 UTC, irenhh commented on src/App.js
> +      : ''
what are you trying to check here? 
(this.addOne - true) OR ((this.state.count + 1) % 5 === 0 - true)?

2020-09-07 08:29 UTC, Denchepornyuk approved these changes

2020-10-28 20:21 UTC, closed without merging