develop
mate-academy/react_counter pull request #259
Opened 2021-01-18 14:23 UTC by Layrovell

[DEMO LINK](https://Layrovell>.github.io/react_counter/)

2021-01-18 20:31 UTC, Serhii-Alieksieievych requested changes
buttons "add100" and "increase" are reversed..

2021-01-18 21:39 UTC, Serhii-Alieksieievych approved these changes

2021-01-19 07:39 UTC, varseniuk approved these changes
Good 👍

2021-01-19 07:39 UTC, varseniuk commented on src/App.js
> +    if (!(this.state.count % 5)) {
```suggestion
    if (!this.state.count % 5) {
```

2021-01-19 09:03 UTC, Serhii-Alieksieievych approved these changes

2021-01-19 09:08 UTC, varseniuk approved these changes

2023-04-05 21:31 UTC, closed without merging