solution
mate-academy/react_counter pull request #519
Opened 2021-09-08 13:38 UTC by Vova-Stoliar

[DEMO LINK](https://Vova-Stoliar.github.io/react_counter/)

2021-09-09 04:45 UTC, ihor-shapoval requested changes

2021-09-09 04:45 UTC, ihor-shapoval commented on src/App.tsx
> +      number += number % 5 ? 1 : 100;
Твой метод increase работает не правильно, он должен каждый раз вызывать addOne, а в случае выполнения условия (number % 5) вызывать addOne и дополнительно add100, у тебя получаеться вызываеться add100 и на этом застревает,так как не меняется условие.

2021-09-09 04:45 UTC, ihor-shapoval commented on src/App.scss
> +}
Добавь пустую строку

2021-09-09 08:16 UTC, Denchepornyuk requested changes

2021-09-09 08:16 UTC, Denchepornyuk commented on src/App.tsx
> +    });
можна скоротити
```suggestion
    this.setState((currentState) => ({
      number: currentState.number + 1
    }));
```

2021-09-09 08:16 UTC, Denchepornyuk commented on src/App.tsx
> +      };
тут також можна скоротити

2021-09-09 08:16 UTC, Denchepornyuk commented on src/App.tsx
> +    }
напиши умову if тільки для this.add100(); а this.addOne(); викликай завжди в методі increase

2021-09-10 10:55 UTC, Denchepornyuk approved these changes

2023-01-12 09:40 UTC, closed without merging