Bes constantine
mate-academy/react_counter pull request #558
Opened 2021-10-15 11:05 UTC by BesConstantine

[DEMO LINK](https://besconstantine.github.io/react_counter/)

2021-10-15 14:41 UTC, io-med approved these changes
Good job!

2021-10-18 08:23 UTC, OleksiiBlezniuk requested changes
Нужно кое-что изменить 🙂

2021-10-18 08:23 UTC, OleksiiBlezniuk commented on src/components/Counter/Counter.tsx
> +    counter: 0,
```suggestion
    count: 0,
```

2021-10-18 08:23 UTC, OleksiiBlezniuk commented on src/components/Counter/Counter.tsx
> +        </button>
Вынеси кнопку в отдельный компонент и передавай название и callback через пропсы 🙂

2023-06-13 15:58 UTC, closed without merging