solution
mate-academy/react_counter pull request #566
Opened 2021-10-15 14:31 UTC by Ruslan-Mykhalchak

[DEMO LINK](https://Ruslan-Mykhalchak.github.io/react_counter/)

2021-10-16 19:07 UTC, Artem5457 approved these changes
It works correctly

2021-10-18 08:21 UTC, aliceblunt8 requested changes

2021-10-18 08:21 UTC, aliceblunt8 commented on src/App.scss
> +}
remove empty spaces from your scss

```suggestion
body {
  background-color: bisque;
}

.container {
  width: 400px;
  margin: 10px auto;
}

.title {
  text-align: center;
  color: rgb(201, 111, 0);
}

.buttons {
  display: flex;
  justify-content: space-between;
}

.button {
  border: none;
  background-color: rgb(241, 170, 82);
  width: 80px;
  height: 30px;
  border-radius: 10px;
  transition: 0.5s;
  cursor: pointer;
 
  &:hover {
    background-color: rgb(201, 111, 0);
    transform: scale(120%);
  }
}
```

2021-10-18 08:21 UTC, aliceblunt8 commented on src/App.tsx
> +      count: prevState.count % 5 === 0 ? (prevState.count + 101) : (prevState.count + 1),
this function should call addOne or add100 depending on `prevState.count % 5 === 0`

2021-10-18 08:21 UTC, aliceblunt8 commented on src/App.tsx
> +  };
```suggestion
  reset = () => {
    this.setState({ count: 0 });
  };
```

2021-10-18 12:51 UTC, aliceblunt8 approved these changes

2024-09-29 08:44 UTC, closed without merging