solution
mate-academy/react_counter pull request #570
Opened 2021-10-16 15:46 UTC by Tarasulko

[DEMO LINK](https://tarasulko.github.io/react_counter/)

2021-10-16 19:02 UTC, Artem5457 requested changes

2021-10-18 08:29 UTC, aliceblunt8 requested changes

2021-10-18 08:29 UTC, aliceblunt8 commented on src/components/Counter.scss
> +}
add empty file at the end of the file

2021-10-18 08:29 UTC, aliceblunt8 commented on src/components/Counter.tsx
> +  state = {
```suggestion
  state: State = {
```

2021-10-18 08:29 UTC, aliceblunt8 commented on src/components/Counter.tsx
> +    this.setState((currState) => ({ number: currState.number + 1 }));
```suggestion
    this.setState((prevState) => ({ number: prevState.number + 1 }));
```

2021-10-18 08:29 UTC, aliceblunt8 commented on src/components/Counter.tsx
> +      return;
remove return, so it always add one initially or after adding 100

```suggestion
```

2021-10-18 08:29 UTC, aliceblunt8 commented on src/components/Counter.tsx
> +        </button>
move props to the new line when they're more than 2 of them

```suggestion
        <button
          type="button"
          className="Counter__button"
          onClick={this.addOne}
        >
          Add 1
        </button>
```

2021-10-18 11:28 UTC, aliceblunt8 approved these changes

2021-10-18 11:28 UTC, aliceblunt8 commented on src/components/Counter.tsx
> +        >
```suggestion
        <button
          type="button"
          className="Counter__button"
          onClick={this.add100}
        >
          Add 100
        </button>
        <button
          type="button"
          className="Counter__button"
          onClick={this.addOneOr100}
        >
```

2024-10-22 13:57 UTC, closed without merging