Task was solved
mate-academy/react_counter pull request #596
Opened 2021-11-10 14:23 UTC by cyb1ove

[DEMO LINK](https://cyb1ove.github.io/react_counter/)

2021-11-10 16:44 UTC, dima-narozhnyi approved these changes
All looks good 👍

2021-11-11 11:14 UTC, solaryasha requested changes

2021-11-11 11:14 UTC, solaryasha commented on src/App.scss
> +  // border: 1px solid black;
Не залишай коментарів

2021-11-11 11:14 UTC, solaryasha commented on src/App.tsx
> +    if (counter && counter % 5 === 0) {
So the third button should count like this: 101, 102, 103, 104, 105, 206, 207, 208, 209, 210, 311 ...

2021-11-11 11:40 UTC, solaryasha approved these changes

2025-01-20 16:30 UTC, closed without merging