solution
mate-academy/react_counter pull request #684
Opened 2022-01-21 18:08 UTC by vladyslav-harkusha

[DEMO LINK](https://vladyslav-harkusha.github.io/react_counter/)

2022-01-21 19:18 UTC, JHesher approved these changes

2022-01-25 13:34 UTC, danheim requested changes

2022-01-25 13:34 UTC, danheim commented on src/App.tsx
> +      : this.addOne()
rewrite using if else
тернарный оператор нужен чтобы выбрать между двух значений, а не выполнять операции

2022-01-26 09:40 UTC, danheim approved these changes

2022-10-17 10:18 UTC, closed without merging