Solution
mate-academy/react_counter pull request #823
Opened 2022-05-10 19:18 UTC by YegorKochetkov

[DEMO LINK](https://yegorkochetkov.github.io/react_counter/)

2022-05-11 06:13 UTC, Anastasiia-Sharkova approved these changes
👍

2022-05-11 09:47 UTC, Andr1yK requested changes
Круто, що ти виніс в окремий компонент.. но власне, а де він?)

2022-05-11 10:18 UTC, YegorKochetkov commented
> Круто, що ти виніс в окремий компонент.. но власне, а де він?)

oops! i did it again...

2022-05-12 08:42 UTC, Andr1yK approved these changes

2022-05-12 08:42 UTC, Andr1yK commented on src/App.tsx
> +        increase={this.increase}
ух.. lifting state up 🔥

2025-04-25 20:15 UTC, closed without merging