solution
mate-academy/react_counter pull request #846
Opened 2022-06-02 07:23 UTC by ZUBOV-ILLIA

[DEMO LINK](https://ZUBOV-ILLIA.github.io/react_counter/)

2022-06-02 08:50 UTC, vlasiuk-anatolii approved these changes

2022-06-02 15:48 UTC, Anna-Tkachenko requested changes
All buttons and functions should be in separate Counter component
Also add some styles to your page, try to use bulma

2022-06-06 12:56 UTC, Denchepornyuk requested changes

2022-06-06 12:56 UTC, Denchepornyuk commented on src/components/Counter.tsx
> +          }}
```suggestion
          onClick={this.addOne}
```
you can remove the arrow function because method addOne doesn't accept  any arguments

2022-06-06 12:56 UTC, Denchepornyuk commented on src/components/Counter.tsx
> +          }}
```suggestion
          onClick={this.add100}
```

2022-06-07 14:06 UTC, Denchepornyuk requested changes

2022-06-07 17:46 UTC, Denchepornyuk approved these changes

2025-03-11 09:22 UTC, closed without merging